apiVersion: meta.dev.upbound.io/v2alpha1
kind: Project
metadata:
  name: configuration-aws-vpc
spec:
  dependsOn:
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    package: xpkg.upbound.io/upbound/provider-aws-ec2
    version: v2.3.0
  - apiVersion: pkg.crossplane.io/v1
    kind: Function
    package: xpkg.upbound.io/crossplane-contrib/function-auto-ready
    version: '>=v0.0.0'
  description: This is where you can describe your project.
  license: Apache-2.0
  maintainer: Upbound User <user@example.com>
  readme: |
    This is where you can add a readme for your project.
  repository: xpkg.upbound.io/solutions/configuration-aws-vpc
  source: github.com/upbound/project-template-scratch
