apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: vpcs.aws.platform.upbound.io
spec:
  compositeTypeRef:
    apiVersion: aws.platform.upbound.io/v1alpha1
    kind: VPC
  mode: Pipeline
  pipeline:
  - functionRef:
      name: solutions-configuration-aws-vpcvpc
    step: vpc-resources
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
